layout_spectrum: 0.7489477143356448
typography_spectrum: 0.06981405888001739
color:
  saturation: 0.23501201836401506
  brandStrength: 0.7074008808950755
  lightness: 0.9605447204100281
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.625853850899338
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-634542-83
  facebook: null
author:
  url: ''
  email: ''
  name: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1743bc7f-aa54-47de-9854-93203f036f8a.png
name: berlo.ro
url: 'http://berlo.ro/'
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/949bbc70-8faf-4102-b0a1-8cfcca0f8acd.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
purpose: []
description: ''
